{
 "title": "WireGuard",
 "tags": [
  "prometheus",
  "network"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "friendly_name",
    "label": "VPN User",
    "query": {
     "query": "label_values(wireguard_latest_handshake_seconds,friendly_name)"
    }
   },
   {
    "name": "job",
    "label": "Node",
    "query": {
     "query": "label_values(wireguard_latest_handshake_seconds,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Latest Handshake",
   "type": "table-old",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "time() - wireguard_latest_handshake_seconds{job=\"$job\"}",
     "legendFormat": "{{allowed_ips}} ({{friendly_name}})"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 17, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "irate(wireguard_received_bytes_total{friendly_name=~\"$friendly_name\"}[$__interval])",
     "legendFormat": "received {{friendly_name}}"
    },
    {
     "expr": "-irate(wireguard_sent_bytes_total{friendly_name=~\"$friendly_name\"}[5m])",
     "legendFormat": "sent {{friendly_name}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(wireguard_sent_bytes_total[$__interval]))",
     "legendFormat": "Total WG traffic"
    }
   ]
  },
  {
   "title": "Traffic by User",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (increase(wireguard_sent_bytes_total{friendly_name=~\"$friendly_name\"}[$__interval])) by (friendly_name)",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Received Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(wireguard_received_bytes_total{job=\"$job\"}[5m])",
     "legendFormat": "{{allowed_ips}} ({{friendly_name}})"
    }
   ]
  },
  {
   "title": "Sent Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(wireguard_sent_bytes_total{job=\"$job\"}[5m])",
     "legendFormat": "{{allowed_ips}} ({{friendly_name}})"
    }
   ]
  }
 ]
}