route:
    receiver: 'slack'
receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            text: "{{ .CommonAnnotations.description }}"
            username: 'Prometheus'
            channel: '#prometheus'
            api_url: 'https://hooks.slack.com/services/T011UM3R8BT/B011JKPK610/xxxxxxxxx' 
      email_configs:
        - to: wg@sandysend.com
          from: wg2@sandysend.com
          smarthost: smtp.gmail.com:587
          auth_username: "wg2@sandysend.com"
          auth_identity: "wg2@sandysend.com"
          auth_password: "xxxxxxxxxxxxxxxxxx"
      telegram_configs:
        - bot_token: YOUR_BOT_TOKEN
          api_url: https://api.telegram.org
          chat_id: YOUR_CHAT_ID
          parse_mode: ''
